// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_fixed_hex`, `group_id_from_hex`, `parse_tags_json`, `serialize_tags`, `summarize_group`, `summarize_pending_welcome`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MdkRuntime`

Future<String> bridgeVersion() =>
    MdkBridgeApi.instance.api.crateApiBridgeVersion();

Future<String> initMdkUnencrypted({required String dataDir}) =>
    MdkBridgeApi.instance.api.crateApiInitMdkUnencrypted(dataDir: dataDir);

Future<String> mdkDbPath() => MdkBridgeApi.instance.api.crateApiMdkDbPath();

Future<int> groupCount() => MdkBridgeApi.instance.api.crateApiGroupCount();

Future<List<String>> groupSummaries() =>
    MdkBridgeApi.instance.api.crateApiGroupSummaries();

Future<List<GroupSummaryData>> getGroupSummaries() =>
    MdkBridgeApi.instance.api.crateApiGetGroupSummaries();

Future<KeyPackageEventData> createKeyPackageEvent({
  required String publicKeyHex,
  required List<String> relays,
}) => MdkBridgeApi.instance.api.crateApiCreateKeyPackageEvent(
  publicKeyHex: publicKeyHex,
  relays: relays,
);

Future<GroupSummaryData> createLocalGroup({
  required String creatorPublicKeyHex,
  required String name,
  required String description,
  required List<String> relays,
  required List<String> memberKeyPackageEventJsons,
}) => MdkBridgeApi.instance.api.crateApiCreateLocalGroup(
  creatorPublicKeyHex: creatorPublicKeyHex,
  name: name,
  description: description,
  relays: relays,
  memberKeyPackageEventJsons: memberKeyPackageEventJsons,
);

Future<CreateGroupWithWelcomesData> createLocalGroupWithWelcomes({
  required String creatorPublicKeyHex,
  required String name,
  required String description,
  required List<String> relays,
  required List<String> memberKeyPackageEventJsons,
}) => MdkBridgeApi.instance.api.crateApiCreateLocalGroupWithWelcomes(
  creatorPublicKeyHex: creatorPublicKeyHex,
  name: name,
  description: description,
  relays: relays,
  memberKeyPackageEventJsons: memberKeyPackageEventJsons,
);

Future<PendingWelcomeData> processWelcomeRumor({
  required String welcomeRumorJson,
}) => MdkBridgeApi.instance.api.crateApiProcessWelcomeRumor(
  welcomeRumorJson: welcomeRumorJson,
);

Future<List<PendingWelcomeData>> getPendingWelcomeSummaries() =>
    MdkBridgeApi.instance.api.crateApiGetPendingWelcomeSummaries();

Future<GroupSummaryData> acceptPendingWelcome({
  required String welcomeEventIdHex,
}) => MdkBridgeApi.instance.api.crateApiAcceptPendingWelcome(
  welcomeEventIdHex: welcomeEventIdHex,
);

Future<List<String>> getGroupMembers({required String mlsGroupIdHex}) =>
    MdkBridgeApi.instance.api.crateApiGetGroupMembers(
      mlsGroupIdHex: mlsGroupIdHex,
    );

Future<GroupUpdateData> removeGroupMembers({
  required String mlsGroupIdHex,
  required List<String> memberPubkeysHex,
}) => MdkBridgeApi.instance.api.crateApiRemoveGroupMembers(
  mlsGroupIdHex: mlsGroupIdHex,
  memberPubkeysHex: memberPubkeysHex,
);

Future<MessageEventData> createApplicationMessage({
  required String mlsGroupIdHex,
  required String senderPublicKeyHex,
  required int kind,
  required String content,
  String? tagsJson,
  BigInt? createdAt,
}) => MdkBridgeApi.instance.api.crateApiCreateApplicationMessage(
  mlsGroupIdHex: mlsGroupIdHex,
  senderPublicKeyHex: senderPublicKeyHex,
  kind: kind,
  content: content,
  tagsJson: tagsJson,
  createdAt: createdAt,
);

Future<EncryptedMediaData> encryptMedia({
  required String mlsGroupIdHex,
  required List<int> bytes,
  required String mimeType,
  required String filename,
}) => MdkBridgeApi.instance.api.crateApiEncryptMedia(
  mlsGroupIdHex: mlsGroupIdHex,
  bytes: bytes,
  mimeType: mimeType,
  filename: filename,
);

Future<Uint8List> decryptMedia({
  required String mlsGroupIdHex,
  required List<int> encryptedBytes,
  required String originalHashHex,
  required String mimeType,
  required String filename,
  required String nonceHex,
  required String schemeVersion,
  required String url,
}) => MdkBridgeApi.instance.api.crateApiDecryptMedia(
  mlsGroupIdHex: mlsGroupIdHex,
  encryptedBytes: encryptedBytes,
  originalHashHex: originalHashHex,
  mimeType: mimeType,
  filename: filename,
  nonceHex: nonceHex,
  schemeVersion: schemeVersion,
  url: url,
);

Future<ProcessedMessageData> processMessageEvent({required String eventJson}) =>
    MdkBridgeApi.instance.api.crateApiProcessMessageEvent(eventJson: eventJson);

class CreateGroupWithWelcomesData {
  final GroupSummaryData group;
  final List<String> welcomeRumorJsons;

  const CreateGroupWithWelcomesData({
    required this.group,
    required this.welcomeRumorJsons,
  });

  @override
  int get hashCode => group.hashCode ^ welcomeRumorJsons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateGroupWithWelcomesData &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          welcomeRumorJsons == other.welcomeRumorJsons;
}

class EncryptedMediaData {
  final Uint8List encryptedData;
  final String encryptedHashHex;
  final String originalHashHex;
  final String mimeType;
  final String filename;
  final BigInt originalSize;
  final BigInt encryptedSize;
  final String nonceHex;
  final String schemeVersion;
  final BigInt epoch;

  const EncryptedMediaData({
    required this.encryptedData,
    required this.encryptedHashHex,
    required this.originalHashHex,
    required this.mimeType,
    required this.filename,
    required this.originalSize,
    required this.encryptedSize,
    required this.nonceHex,
    required this.schemeVersion,
    required this.epoch,
  });

  @override
  int get hashCode =>
      encryptedData.hashCode ^
      encryptedHashHex.hashCode ^
      originalHashHex.hashCode ^
      mimeType.hashCode ^
      filename.hashCode ^
      originalSize.hashCode ^
      encryptedSize.hashCode ^
      nonceHex.hashCode ^
      schemeVersion.hashCode ^
      epoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedMediaData &&
          runtimeType == other.runtimeType &&
          encryptedData == other.encryptedData &&
          encryptedHashHex == other.encryptedHashHex &&
          originalHashHex == other.originalHashHex &&
          mimeType == other.mimeType &&
          filename == other.filename &&
          originalSize == other.originalSize &&
          encryptedSize == other.encryptedSize &&
          nonceHex == other.nonceHex &&
          schemeVersion == other.schemeVersion &&
          epoch == other.epoch;
}

class GroupSummaryData {
  final String mlsGroupIdHex;
  final String nostrGroupIdHex;
  final String name;
  final String description;
  final int memberCount;
  final List<String> adminPubkeysHex;

  const GroupSummaryData({
    required this.mlsGroupIdHex,
    required this.nostrGroupIdHex,
    required this.name,
    required this.description,
    required this.memberCount,
    required this.adminPubkeysHex,
  });

  @override
  int get hashCode =>
      mlsGroupIdHex.hashCode ^
      nostrGroupIdHex.hashCode ^
      name.hashCode ^
      description.hashCode ^
      memberCount.hashCode ^
      adminPubkeysHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupSummaryData &&
          runtimeType == other.runtimeType &&
          mlsGroupIdHex == other.mlsGroupIdHex &&
          nostrGroupIdHex == other.nostrGroupIdHex &&
          name == other.name &&
          description == other.description &&
          memberCount == other.memberCount &&
          adminPubkeysHex == other.adminPubkeysHex;
}

class GroupUpdateData {
  final String wrapperEventJson;
  final String wrapperEventIdHex;
  final String mlsGroupIdHex;

  const GroupUpdateData({
    required this.wrapperEventJson,
    required this.wrapperEventIdHex,
    required this.mlsGroupIdHex,
  });

  @override
  int get hashCode =>
      wrapperEventJson.hashCode ^
      wrapperEventIdHex.hashCode ^
      mlsGroupIdHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupUpdateData &&
          runtimeType == other.runtimeType &&
          wrapperEventJson == other.wrapperEventJson &&
          wrapperEventIdHex == other.wrapperEventIdHex &&
          mlsGroupIdHex == other.mlsGroupIdHex;
}

class KeyPackageEventData {
  final String content;
  final String tagsJson;
  final String hashRefHex;

  const KeyPackageEventData({
    required this.content,
    required this.tagsJson,
    required this.hashRefHex,
  });

  @override
  int get hashCode =>
      content.hashCode ^ tagsJson.hashCode ^ hashRefHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageEventData &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          tagsJson == other.tagsJson &&
          hashRefHex == other.hashRefHex;
}

class MessageEventData {
  final String wrapperEventJson;
  final String wrapperEventIdHex;
  final String rumorEventIdHex;
  final String mlsGroupIdHex;

  const MessageEventData({
    required this.wrapperEventJson,
    required this.wrapperEventIdHex,
    required this.rumorEventIdHex,
    required this.mlsGroupIdHex,
  });

  @override
  int get hashCode =>
      wrapperEventJson.hashCode ^
      wrapperEventIdHex.hashCode ^
      rumorEventIdHex.hashCode ^
      mlsGroupIdHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageEventData &&
          runtimeType == other.runtimeType &&
          wrapperEventJson == other.wrapperEventJson &&
          wrapperEventIdHex == other.wrapperEventIdHex &&
          rumorEventIdHex == other.rumorEventIdHex &&
          mlsGroupIdHex == other.mlsGroupIdHex;
}

class PendingWelcomeData {
  final String welcomeEventIdHex;
  final String wrapperEventIdHex;
  final String mlsGroupIdHex;
  final String nostrGroupIdHex;
  final String groupName;
  final String groupDescription;
  final int memberCount;
  final String welcomerPubkeyHex;
  final List<String> relays;
  final String state;

  const PendingWelcomeData({
    required this.welcomeEventIdHex,
    required this.wrapperEventIdHex,
    required this.mlsGroupIdHex,
    required this.nostrGroupIdHex,
    required this.groupName,
    required this.groupDescription,
    required this.memberCount,
    required this.welcomerPubkeyHex,
    required this.relays,
    required this.state,
  });

  @override
  int get hashCode =>
      welcomeEventIdHex.hashCode ^
      wrapperEventIdHex.hashCode ^
      mlsGroupIdHex.hashCode ^
      nostrGroupIdHex.hashCode ^
      groupName.hashCode ^
      groupDescription.hashCode ^
      memberCount.hashCode ^
      welcomerPubkeyHex.hashCode ^
      relays.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingWelcomeData &&
          runtimeType == other.runtimeType &&
          welcomeEventIdHex == other.welcomeEventIdHex &&
          wrapperEventIdHex == other.wrapperEventIdHex &&
          mlsGroupIdHex == other.mlsGroupIdHex &&
          nostrGroupIdHex == other.nostrGroupIdHex &&
          groupName == other.groupName &&
          groupDescription == other.groupDescription &&
          memberCount == other.memberCount &&
          welcomerPubkeyHex == other.welcomerPubkeyHex &&
          relays == other.relays &&
          state == other.state;
}

class ProcessedMessageData {
  final String outcome;
  final String mlsGroupIdHex;
  final String messageEventIdHex;
  final String wrapperEventIdHex;
  final String pubkeyHex;
  final int kind;
  final String content;
  final BigInt createdAt;
  final String state;

  const ProcessedMessageData({
    required this.outcome,
    required this.mlsGroupIdHex,
    required this.messageEventIdHex,
    required this.wrapperEventIdHex,
    required this.pubkeyHex,
    required this.kind,
    required this.content,
    required this.createdAt,
    required this.state,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^
      mlsGroupIdHex.hashCode ^
      messageEventIdHex.hashCode ^
      wrapperEventIdHex.hashCode ^
      pubkeyHex.hashCode ^
      kind.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedMessageData &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          mlsGroupIdHex == other.mlsGroupIdHex &&
          messageEventIdHex == other.messageEventIdHex &&
          wrapperEventIdHex == other.wrapperEventIdHex &&
          pubkeyHex == other.pubkeyHex &&
          kind == other.kind &&
          content == other.content &&
          createdAt == other.createdAt &&
          state == other.state;
}
