// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class MdkBridgeApiApiImplPlatform
    extends BaseApiImpl<MdkBridgeApiWire> {
  MdkBridgeApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CreateGroupWithWelcomesData dco_decode_create_group_with_welcomes_data(
    dynamic raw,
  );

  @protected
  EncryptedMediaData dco_decode_encrypted_media_data(dynamic raw);

  @protected
  GroupSummaryData dco_decode_group_summary_data(dynamic raw);

  @protected
  GroupUpdateData dco_decode_group_update_data(dynamic raw);

  @protected
  KeyPackageEventData dco_decode_key_package_event_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<GroupSummaryData> dco_decode_list_group_summary_data(dynamic raw);

  @protected
  List<PendingWelcomeData> dco_decode_list_pending_welcome_data(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MessageEventData dco_decode_message_event_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PendingWelcomeData dco_decode_pending_welcome_data(dynamic raw);

  @protected
  ProcessedMessageData dco_decode_processed_message_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CreateGroupWithWelcomesData sse_decode_create_group_with_welcomes_data(
    SseDeserializer deserializer,
  );

  @protected
  EncryptedMediaData sse_decode_encrypted_media_data(
    SseDeserializer deserializer,
  );

  @protected
  GroupSummaryData sse_decode_group_summary_data(SseDeserializer deserializer);

  @protected
  GroupUpdateData sse_decode_group_update_data(SseDeserializer deserializer);

  @protected
  KeyPackageEventData sse_decode_key_package_event_data(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<GroupSummaryData> sse_decode_list_group_summary_data(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingWelcomeData> sse_decode_list_pending_welcome_data(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MessageEventData sse_decode_message_event_data(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PendingWelcomeData sse_decode_pending_welcome_data(
    SseDeserializer deserializer,
  );

  @protected
  ProcessedMessageData sse_decode_processed_message_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_create_group_with_welcomes_data(
    CreateGroupWithWelcomesData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encrypted_media_data(
    EncryptedMediaData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_summary_data(
    GroupSummaryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_update_data(
    GroupUpdateData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_package_event_data(
    KeyPackageEventData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_summary_data(
    List<GroupSummaryData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_welcome_data(
    List<PendingWelcomeData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_event_data(
    MessageEventData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pending_welcome_data(
    PendingWelcomeData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_message_data(
    ProcessedMessageData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class MdkBridgeApiWire implements BaseWire {
  factory MdkBridgeApiWire.fromExternalLibrary(ExternalLibrary lib) =>
      MdkBridgeApiWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MdkBridgeApiWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
