// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class MdkBridgeApi
    extends
        BaseEntrypoint<MdkBridgeApiApi, MdkBridgeApiApiImpl, MdkBridgeApiWire> {
  @internal
  static final instance = MdkBridgeApi._();

  MdkBridgeApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    MdkBridgeApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required MdkBridgeApiApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<MdkBridgeApiApiImpl, MdkBridgeApiWire>
  get apiImplConstructor => MdkBridgeApiApiImpl.new;

  @override
  WireConstructor<MdkBridgeApiWire> get wireConstructor =>
      MdkBridgeApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 452026429;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mdk_bridge',
        ioDirectory: 'native/mdk_bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class MdkBridgeApiApi extends BaseApi {
  Future<GroupSummaryData> crateApiAcceptPendingWelcome({
    required String welcomeEventIdHex,
  });

  Future<String> crateApiBridgeVersion();

  Future<MessageEventData> crateApiCreateApplicationMessage({
    required String mlsGroupIdHex,
    required String senderPublicKeyHex,
    required int kind,
    required String content,
    String? tagsJson,
    BigInt? createdAt,
  });

  Future<KeyPackageEventData> crateApiCreateKeyPackageEvent({
    required String publicKeyHex,
    required List<String> relays,
  });

  Future<GroupSummaryData> crateApiCreateLocalGroup({
    required String creatorPublicKeyHex,
    required String name,
    required String description,
    required List<String> relays,
    required List<String> memberKeyPackageEventJsons,
  });

  Future<CreateGroupWithWelcomesData> crateApiCreateLocalGroupWithWelcomes({
    required String creatorPublicKeyHex,
    required String name,
    required String description,
    required List<String> relays,
    required List<String> memberKeyPackageEventJsons,
  });

  Future<Uint8List> crateApiDecryptMedia({
    required String mlsGroupIdHex,
    required List<int> encryptedBytes,
    required String originalHashHex,
    required String mimeType,
    required String filename,
    required String nonceHex,
    required String schemeVersion,
    required String url,
  });

  Future<EncryptedMediaData> crateApiEncryptMedia({
    required String mlsGroupIdHex,
    required List<int> bytes,
    required String mimeType,
    required String filename,
  });

  Future<List<String>> crateApiGetGroupMembers({required String mlsGroupIdHex});

  Future<List<GroupSummaryData>> crateApiGetGroupSummaries();

  Future<List<PendingWelcomeData>> crateApiGetPendingWelcomeSummaries();

  Future<int> crateApiGroupCount();

  Future<List<String>> crateApiGroupSummaries();

  Future<String> crateApiInitMdkUnencrypted({required String dataDir});

  Future<String> crateApiMdkDbPath();

  Future<ProcessedMessageData> crateApiProcessMessageEvent({
    required String eventJson,
  });

  Future<PendingWelcomeData> crateApiProcessWelcomeRumor({
    required String welcomeRumorJson,
  });

  Future<GroupUpdateData> crateApiRemoveGroupMembers({
    required String mlsGroupIdHex,
    required List<String> memberPubkeysHex,
  });
}

class MdkBridgeApiApiImpl extends MdkBridgeApiApiImplPlatform
    implements MdkBridgeApiApi {
  MdkBridgeApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<GroupSummaryData> crateApiAcceptPendingWelcome({
    required String welcomeEventIdHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(welcomeEventIdHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_group_summary_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAcceptPendingWelcomeConstMeta,
        argValues: [welcomeEventIdHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAcceptPendingWelcomeConstMeta =>
      const TaskConstMeta(
        debugName: "accept_pending_welcome",
        argNames: ["welcomeEventIdHex"],
      );

  @override
  Future<String> crateApiBridgeVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeVersionConstMeta =>
      const TaskConstMeta(debugName: "bridge_version", argNames: []);

  @override
  Future<MessageEventData> crateApiCreateApplicationMessage({
    required String mlsGroupIdHex,
    required String senderPublicKeyHex,
    required int kind,
    required String content,
    String? tagsJson,
    BigInt? createdAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mlsGroupIdHex, serializer);
          sse_encode_String(senderPublicKeyHex, serializer);
          sse_encode_u_32(kind, serializer);
          sse_encode_String(content, serializer);
          sse_encode_opt_String(tagsJson, serializer);
          sse_encode_opt_box_autoadd_u_64(createdAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_event_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateApplicationMessageConstMeta,
        argValues: [
          mlsGroupIdHex,
          senderPublicKeyHex,
          kind,
          content,
          tagsJson,
          createdAt,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateApplicationMessageConstMeta =>
      const TaskConstMeta(
        debugName: "create_application_message",
        argNames: [
          "mlsGroupIdHex",
          "senderPublicKeyHex",
          "kind",
          "content",
          "tagsJson",
          "createdAt",
        ],
      );

  @override
  Future<KeyPackageEventData> crateApiCreateKeyPackageEvent({
    required String publicKeyHex,
    required List<String> relays,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKeyHex, serializer);
          sse_encode_list_String(relays, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_package_event_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateKeyPackageEventConstMeta,
        argValues: [publicKeyHex, relays],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateKeyPackageEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_key_package_event",
        argNames: ["publicKeyHex", "relays"],
      );

  @override
  Future<GroupSummaryData> crateApiCreateLocalGroup({
    required String creatorPublicKeyHex,
    required String name,
    required String description,
    required List<String> relays,
    required List<String> memberKeyPackageEventJsons,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(creatorPublicKeyHex, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(description, serializer);
          sse_encode_list_String(relays, serializer);
          sse_encode_list_String(memberKeyPackageEventJsons, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_group_summary_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateLocalGroupConstMeta,
        argValues: [
          creatorPublicKeyHex,
          name,
          description,
          relays,
          memberKeyPackageEventJsons,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateLocalGroupConstMeta => const TaskConstMeta(
    debugName: "create_local_group",
    argNames: [
      "creatorPublicKeyHex",
      "name",
      "description",
      "relays",
      "memberKeyPackageEventJsons",
    ],
  );

  @override
  Future<CreateGroupWithWelcomesData> crateApiCreateLocalGroupWithWelcomes({
    required String creatorPublicKeyHex,
    required String name,
    required String description,
    required List<String> relays,
    required List<String> memberKeyPackageEventJsons,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(creatorPublicKeyHex, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(description, serializer);
          sse_encode_list_String(relays, serializer);
          sse_encode_list_String(memberKeyPackageEventJsons, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_create_group_with_welcomes_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateLocalGroupWithWelcomesConstMeta,
        argValues: [
          creatorPublicKeyHex,
          name,
          description,
          relays,
          memberKeyPackageEventJsons,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateLocalGroupWithWelcomesConstMeta =>
      const TaskConstMeta(
        debugName: "create_local_group_with_welcomes",
        argNames: [
          "creatorPublicKeyHex",
          "name",
          "description",
          "relays",
          "memberKeyPackageEventJsons",
        ],
      );

  @override
  Future<Uint8List> crateApiDecryptMedia({
    required String mlsGroupIdHex,
    required List<int> encryptedBytes,
    required String originalHashHex,
    required String mimeType,
    required String filename,
    required String nonceHex,
    required String schemeVersion,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mlsGroupIdHex, serializer);
          sse_encode_list_prim_u_8_loose(encryptedBytes, serializer);
          sse_encode_String(originalHashHex, serializer);
          sse_encode_String(mimeType, serializer);
          sse_encode_String(filename, serializer);
          sse_encode_String(nonceHex, serializer);
          sse_encode_String(schemeVersion, serializer);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDecryptMediaConstMeta,
        argValues: [
          mlsGroupIdHex,
          encryptedBytes,
          originalHashHex,
          mimeType,
          filename,
          nonceHex,
          schemeVersion,
          url,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecryptMediaConstMeta => const TaskConstMeta(
    debugName: "decrypt_media",
    argNames: [
      "mlsGroupIdHex",
      "encryptedBytes",
      "originalHashHex",
      "mimeType",
      "filename",
      "nonceHex",
      "schemeVersion",
      "url",
    ],
  );

  @override
  Future<EncryptedMediaData> crateApiEncryptMedia({
    required String mlsGroupIdHex,
    required List<int> bytes,
    required String mimeType,
    required String filename,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mlsGroupIdHex, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(mimeType, serializer);
          sse_encode_String(filename, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encrypted_media_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEncryptMediaConstMeta,
        argValues: [mlsGroupIdHex, bytes, mimeType, filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptMediaConstMeta => const TaskConstMeta(
    debugName: "encrypt_media",
    argNames: ["mlsGroupIdHex", "bytes", "mimeType", "filename"],
  );

  @override
  Future<List<String>> crateApiGetGroupMembers({
    required String mlsGroupIdHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mlsGroupIdHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetGroupMembersConstMeta,
        argValues: [mlsGroupIdHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetGroupMembersConstMeta => const TaskConstMeta(
    debugName: "get_group_members",
    argNames: ["mlsGroupIdHex"],
  );

  @override
  Future<List<GroupSummaryData>> crateApiGetGroupSummaries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_group_summary_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetGroupSummariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetGroupSummariesConstMeta =>
      const TaskConstMeta(debugName: "get_group_summaries", argNames: []);

  @override
  Future<List<PendingWelcomeData>> crateApiGetPendingWelcomeSummaries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pending_welcome_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetPendingWelcomeSummariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPendingWelcomeSummariesConstMeta =>
      const TaskConstMeta(
        debugName: "get_pending_welcome_summaries",
        argNames: [],
      );

  @override
  Future<int> crateApiGroupCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGroupCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGroupCountConstMeta =>
      const TaskConstMeta(debugName: "group_count", argNames: []);

  @override
  Future<List<String>> crateApiGroupSummaries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGroupSummariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGroupSummariesConstMeta =>
      const TaskConstMeta(debugName: "group_summaries", argNames: []);

  @override
  Future<String> crateApiInitMdkUnencrypted({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitMdkUnencryptedConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitMdkUnencryptedConstMeta => const TaskConstMeta(
    debugName: "init_mdk_unencrypted",
    argNames: ["dataDir"],
  );

  @override
  Future<String> crateApiMdkDbPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMdkDbPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMdkDbPathConstMeta =>
      const TaskConstMeta(debugName: "mdk_db_path", argNames: []);

  @override
  Future<ProcessedMessageData> crateApiProcessMessageEvent({
    required String eventJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_processed_message_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProcessMessageEventConstMeta,
        argValues: [eventJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessMessageEventConstMeta =>
      const TaskConstMeta(
        debugName: "process_message_event",
        argNames: ["eventJson"],
      );

  @override
  Future<PendingWelcomeData> crateApiProcessWelcomeRumor({
    required String welcomeRumorJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(welcomeRumorJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pending_welcome_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProcessWelcomeRumorConstMeta,
        argValues: [welcomeRumorJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessWelcomeRumorConstMeta =>
      const TaskConstMeta(
        debugName: "process_welcome_rumor",
        argNames: ["welcomeRumorJson"],
      );

  @override
  Future<GroupUpdateData> crateApiRemoveGroupMembers({
    required String mlsGroupIdHex,
    required List<String> memberPubkeysHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mlsGroupIdHex, serializer);
          sse_encode_list_String(memberPubkeysHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_group_update_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRemoveGroupMembersConstMeta,
        argValues: [mlsGroupIdHex, memberPubkeysHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveGroupMembersConstMeta => const TaskConstMeta(
    debugName: "remove_group_members",
    argNames: ["mlsGroupIdHex", "memberPubkeysHex"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CreateGroupWithWelcomesData dco_decode_create_group_with_welcomes_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CreateGroupWithWelcomesData(
      group: dco_decode_group_summary_data(arr[0]),
      welcomeRumorJsons: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  EncryptedMediaData dco_decode_encrypted_media_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return EncryptedMediaData(
      encryptedData: dco_decode_list_prim_u_8_strict(arr[0]),
      encryptedHashHex: dco_decode_String(arr[1]),
      originalHashHex: dco_decode_String(arr[2]),
      mimeType: dco_decode_String(arr[3]),
      filename: dco_decode_String(arr[4]),
      originalSize: dco_decode_u_64(arr[5]),
      encryptedSize: dco_decode_u_64(arr[6]),
      nonceHex: dco_decode_String(arr[7]),
      schemeVersion: dco_decode_String(arr[8]),
      epoch: dco_decode_u_64(arr[9]),
    );
  }

  @protected
  GroupSummaryData dco_decode_group_summary_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return GroupSummaryData(
      mlsGroupIdHex: dco_decode_String(arr[0]),
      nostrGroupIdHex: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
      memberCount: dco_decode_u_32(arr[4]),
      adminPubkeysHex: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  GroupUpdateData dco_decode_group_update_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GroupUpdateData(
      wrapperEventJson: dco_decode_String(arr[0]),
      wrapperEventIdHex: dco_decode_String(arr[1]),
      mlsGroupIdHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  KeyPackageEventData dco_decode_key_package_event_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KeyPackageEventData(
      content: dco_decode_String(arr[0]),
      tagsJson: dco_decode_String(arr[1]),
      hashRefHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<GroupSummaryData> dco_decode_list_group_summary_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_group_summary_data).toList();
  }

  @protected
  List<PendingWelcomeData> dco_decode_list_pending_welcome_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pending_welcome_data).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageEventData dco_decode_message_event_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MessageEventData(
      wrapperEventJson: dco_decode_String(arr[0]),
      wrapperEventIdHex: dco_decode_String(arr[1]),
      rumorEventIdHex: dco_decode_String(arr[2]),
      mlsGroupIdHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PendingWelcomeData dco_decode_pending_welcome_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return PendingWelcomeData(
      welcomeEventIdHex: dco_decode_String(arr[0]),
      wrapperEventIdHex: dco_decode_String(arr[1]),
      mlsGroupIdHex: dco_decode_String(arr[2]),
      nostrGroupIdHex: dco_decode_String(arr[3]),
      groupName: dco_decode_String(arr[4]),
      groupDescription: dco_decode_String(arr[5]),
      memberCount: dco_decode_u_32(arr[6]),
      welcomerPubkeyHex: dco_decode_String(arr[7]),
      relays: dco_decode_list_String(arr[8]),
      state: dco_decode_String(arr[9]),
    );
  }

  @protected
  ProcessedMessageData dco_decode_processed_message_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ProcessedMessageData(
      outcome: dco_decode_String(arr[0]),
      mlsGroupIdHex: dco_decode_String(arr[1]),
      messageEventIdHex: dco_decode_String(arr[2]),
      wrapperEventIdHex: dco_decode_String(arr[3]),
      pubkeyHex: dco_decode_String(arr[4]),
      kind: dco_decode_u_32(arr[5]),
      content: dco_decode_String(arr[6]),
      createdAt: dco_decode_u_64(arr[7]),
      state: dco_decode_String(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CreateGroupWithWelcomesData sse_decode_create_group_with_welcomes_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_group = sse_decode_group_summary_data(deserializer);
    var var_welcomeRumorJsons = sse_decode_list_String(deserializer);
    return CreateGroupWithWelcomesData(
      group: var_group,
      welcomeRumorJsons: var_welcomeRumorJsons,
    );
  }

  @protected
  EncryptedMediaData sse_decode_encrypted_media_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_encryptedData = sse_decode_list_prim_u_8_strict(deserializer);
    var var_encryptedHashHex = sse_decode_String(deserializer);
    var var_originalHashHex = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_filename = sse_decode_String(deserializer);
    var var_originalSize = sse_decode_u_64(deserializer);
    var var_encryptedSize = sse_decode_u_64(deserializer);
    var var_nonceHex = sse_decode_String(deserializer);
    var var_schemeVersion = sse_decode_String(deserializer);
    var var_epoch = sse_decode_u_64(deserializer);
    return EncryptedMediaData(
      encryptedData: var_encryptedData,
      encryptedHashHex: var_encryptedHashHex,
      originalHashHex: var_originalHashHex,
      mimeType: var_mimeType,
      filename: var_filename,
      originalSize: var_originalSize,
      encryptedSize: var_encryptedSize,
      nonceHex: var_nonceHex,
      schemeVersion: var_schemeVersion,
      epoch: var_epoch,
    );
  }

  @protected
  GroupSummaryData sse_decode_group_summary_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mlsGroupIdHex = sse_decode_String(deserializer);
    var var_nostrGroupIdHex = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_memberCount = sse_decode_u_32(deserializer);
    var var_adminPubkeysHex = sse_decode_list_String(deserializer);
    return GroupSummaryData(
      mlsGroupIdHex: var_mlsGroupIdHex,
      nostrGroupIdHex: var_nostrGroupIdHex,
      name: var_name,
      description: var_description,
      memberCount: var_memberCount,
      adminPubkeysHex: var_adminPubkeysHex,
    );
  }

  @protected
  GroupUpdateData sse_decode_group_update_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wrapperEventJson = sse_decode_String(deserializer);
    var var_wrapperEventIdHex = sse_decode_String(deserializer);
    var var_mlsGroupIdHex = sse_decode_String(deserializer);
    return GroupUpdateData(
      wrapperEventJson: var_wrapperEventJson,
      wrapperEventIdHex: var_wrapperEventIdHex,
      mlsGroupIdHex: var_mlsGroupIdHex,
    );
  }

  @protected
  KeyPackageEventData sse_decode_key_package_event_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_String(deserializer);
    var var_tagsJson = sse_decode_String(deserializer);
    var var_hashRefHex = sse_decode_String(deserializer);
    return KeyPackageEventData(
      content: var_content,
      tagsJson: var_tagsJson,
      hashRefHex: var_hashRefHex,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<GroupSummaryData> sse_decode_list_group_summary_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GroupSummaryData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_group_summary_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<PendingWelcomeData> sse_decode_list_pending_welcome_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PendingWelcomeData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pending_welcome_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageEventData sse_decode_message_event_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wrapperEventJson = sse_decode_String(deserializer);
    var var_wrapperEventIdHex = sse_decode_String(deserializer);
    var var_rumorEventIdHex = sse_decode_String(deserializer);
    var var_mlsGroupIdHex = sse_decode_String(deserializer);
    return MessageEventData(
      wrapperEventJson: var_wrapperEventJson,
      wrapperEventIdHex: var_wrapperEventIdHex,
      rumorEventIdHex: var_rumorEventIdHex,
      mlsGroupIdHex: var_mlsGroupIdHex,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PendingWelcomeData sse_decode_pending_welcome_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_welcomeEventIdHex = sse_decode_String(deserializer);
    var var_wrapperEventIdHex = sse_decode_String(deserializer);
    var var_mlsGroupIdHex = sse_decode_String(deserializer);
    var var_nostrGroupIdHex = sse_decode_String(deserializer);
    var var_groupName = sse_decode_String(deserializer);
    var var_groupDescription = sse_decode_String(deserializer);
    var var_memberCount = sse_decode_u_32(deserializer);
    var var_welcomerPubkeyHex = sse_decode_String(deserializer);
    var var_relays = sse_decode_list_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    return PendingWelcomeData(
      welcomeEventIdHex: var_welcomeEventIdHex,
      wrapperEventIdHex: var_wrapperEventIdHex,
      mlsGroupIdHex: var_mlsGroupIdHex,
      nostrGroupIdHex: var_nostrGroupIdHex,
      groupName: var_groupName,
      groupDescription: var_groupDescription,
      memberCount: var_memberCount,
      welcomerPubkeyHex: var_welcomerPubkeyHex,
      relays: var_relays,
      state: var_state,
    );
  }

  @protected
  ProcessedMessageData sse_decode_processed_message_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_String(deserializer);
    var var_mlsGroupIdHex = sse_decode_String(deserializer);
    var var_messageEventIdHex = sse_decode_String(deserializer);
    var var_wrapperEventIdHex = sse_decode_String(deserializer);
    var var_pubkeyHex = sse_decode_String(deserializer);
    var var_kind = sse_decode_u_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_state = sse_decode_String(deserializer);
    return ProcessedMessageData(
      outcome: var_outcome,
      mlsGroupIdHex: var_mlsGroupIdHex,
      messageEventIdHex: var_messageEventIdHex,
      wrapperEventIdHex: var_wrapperEventIdHex,
      pubkeyHex: var_pubkeyHex,
      kind: var_kind,
      content: var_content,
      createdAt: var_createdAt,
      state: var_state,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_create_group_with_welcomes_data(
    CreateGroupWithWelcomesData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_group_summary_data(self.group, serializer);
    sse_encode_list_String(self.welcomeRumorJsons, serializer);
  }

  @protected
  void sse_encode_encrypted_media_data(
    EncryptedMediaData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.encryptedData, serializer);
    sse_encode_String(self.encryptedHashHex, serializer);
    sse_encode_String(self.originalHashHex, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_u_64(self.originalSize, serializer);
    sse_encode_u_64(self.encryptedSize, serializer);
    sse_encode_String(self.nonceHex, serializer);
    sse_encode_String(self.schemeVersion, serializer);
    sse_encode_u_64(self.epoch, serializer);
  }

  @protected
  void sse_encode_group_summary_data(
    GroupSummaryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mlsGroupIdHex, serializer);
    sse_encode_String(self.nostrGroupIdHex, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_u_32(self.memberCount, serializer);
    sse_encode_list_String(self.adminPubkeysHex, serializer);
  }

  @protected
  void sse_encode_group_update_data(
    GroupUpdateData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.wrapperEventJson, serializer);
    sse_encode_String(self.wrapperEventIdHex, serializer);
    sse_encode_String(self.mlsGroupIdHex, serializer);
  }

  @protected
  void sse_encode_key_package_event_data(
    KeyPackageEventData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.tagsJson, serializer);
    sse_encode_String(self.hashRefHex, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_group_summary_data(
    List<GroupSummaryData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_group_summary_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pending_welcome_data(
    List<PendingWelcomeData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pending_welcome_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_event_data(
    MessageEventData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.wrapperEventJson, serializer);
    sse_encode_String(self.wrapperEventIdHex, serializer);
    sse_encode_String(self.rumorEventIdHex, serializer);
    sse_encode_String(self.mlsGroupIdHex, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_pending_welcome_data(
    PendingWelcomeData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.welcomeEventIdHex, serializer);
    sse_encode_String(self.wrapperEventIdHex, serializer);
    sse_encode_String(self.mlsGroupIdHex, serializer);
    sse_encode_String(self.nostrGroupIdHex, serializer);
    sse_encode_String(self.groupName, serializer);
    sse_encode_String(self.groupDescription, serializer);
    sse_encode_u_32(self.memberCount, serializer);
    sse_encode_String(self.welcomerPubkeyHex, serializer);
    sse_encode_list_String(self.relays, serializer);
    sse_encode_String(self.state, serializer);
  }

  @protected
  void sse_encode_processed_message_data(
    ProcessedMessageData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outcome, serializer);
    sse_encode_String(self.mlsGroupIdHex, serializer);
    sse_encode_String(self.messageEventIdHex, serializer);
    sse_encode_String(self.wrapperEventIdHex, serializer);
    sse_encode_String(self.pubkeyHex, serializer);
    sse_encode_u_32(self.kind, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_String(self.state, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
