// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -666152521;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__accept_pending_welcome_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_pending_welcome",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_welcome_event_id_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::accept_pending_welcome(api_welcome_event_id_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__bridge_version_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bridge_version",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::bridge_version())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__create_application_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_application_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            let api_sender_public_key_hex = <String>::sse_decode(&mut deserializer);
            let api_kind = <u32>::sse_decode(&mut deserializer);
            let api_content = <String>::sse_decode(&mut deserializer);
            let api_tags_json = <Option<String>>::sse_decode(&mut deserializer);
            let api_created_at = <Option<u64>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::create_application_message(
                        api_mls_group_id_hex,
                        api_sender_public_key_hex,
                        api_kind,
                        api_content,
                        api_tags_json,
                        api_created_at,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__create_key_package_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_key_package_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_public_key_hex = <String>::sse_decode(&mut deserializer);
            let api_relays = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::create_key_package_event(api_public_key_hex, api_relays)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__create_local_group_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_local_group",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_creator_public_key_hex = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_description = <String>::sse_decode(&mut deserializer);
            let api_relays = <Vec<String>>::sse_decode(&mut deserializer);
            let api_member_key_package_event_jsons = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::create_local_group(
                        api_creator_public_key_hex,
                        api_name,
                        api_description,
                        api_relays,
                        api_member_key_package_event_jsons,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__create_local_group_with_welcomes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_local_group_with_welcomes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_creator_public_key_hex = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_description = <String>::sse_decode(&mut deserializer);
            let api_relays = <Vec<String>>::sse_decode(&mut deserializer);
            let api_member_key_package_event_jsons = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::create_local_group_with_welcomes(
                        api_creator_public_key_hex,
                        api_name,
                        api_description,
                        api_relays,
                        api_member_key_package_event_jsons,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__decrypt_media_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decrypt_media",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            let api_encrypted_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_original_hash_hex = <String>::sse_decode(&mut deserializer);
            let api_mime_type = <String>::sse_decode(&mut deserializer);
            let api_filename = <String>::sse_decode(&mut deserializer);
            let api_nonce_hex = <String>::sse_decode(&mut deserializer);
            let api_scheme_version = <String>::sse_decode(&mut deserializer);
            let api_url = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::decrypt_media(
                        api_mls_group_id_hex,
                        api_encrypted_bytes,
                        api_original_hash_hex,
                        api_mime_type,
                        api_filename,
                        api_nonce_hex,
                        api_scheme_version,
                        api_url,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__encrypt_media_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encrypt_media",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_mime_type = <String>::sse_decode(&mut deserializer);
            let api_filename = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::encrypt_media(
                        api_mls_group_id_hex,
                        api_bytes,
                        api_mime_type,
                        api_filename,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_group_members_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_group_members",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::get_group_members(api_mls_group_id_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_group_summaries_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_group_summaries",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::get_group_summaries()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_pending_welcome_summaries_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_pending_welcome_summaries",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::get_pending_welcome_summaries()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__group_count_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "group_count",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::group_count()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__group_summaries_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "group_summaries",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::group_summaries()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__init_mdk_unencrypted_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_mdk_unencrypted",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::init_mdk_unencrypted(api_data_dir)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__leave_group_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "leave_group",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::leave_group(api_mls_group_id_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__mdk_db_path_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mdk_db_path",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::mdk_db_path()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__process_message_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_message_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_event_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::process_message_event(api_event_json)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__process_welcome_rumor_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_welcome_rumor",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_welcome_rumor_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::process_welcome_rumor(api_welcome_rumor_json)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__remove_group_members_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "remove_group_members",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            let api_member_pubkeys_hex = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::remove_group_members(
                        api_mls_group_id_hex,
                        api_member_pubkeys_hex,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__self_demote_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "self_demote",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::self_demote(api_mls_group_id_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__update_group_admins_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_group_admins",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mls_group_id_hex = <String>::sse_decode(&mut deserializer);
            let api_admin_pubkeys_hex = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::update_group_admins(
                        api_mls_group_id_hex,
                        api_admin_pubkeys_hex,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::CreateGroupWithWelcomesData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_group = <crate::api::GroupSummaryData>::sse_decode(deserializer);
        let mut var_welcomeRumorJsons = <Vec<String>>::sse_decode(deserializer);
        return crate::api::CreateGroupWithWelcomesData {
            group: var_group,
            welcome_rumor_jsons: var_welcomeRumorJsons,
        };
    }
}

impl SseDecode for crate::api::EncryptedMediaData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_encryptedData = <Vec<u8>>::sse_decode(deserializer);
        let mut var_encryptedHashHex = <String>::sse_decode(deserializer);
        let mut var_originalHashHex = <String>::sse_decode(deserializer);
        let mut var_mimeType = <String>::sse_decode(deserializer);
        let mut var_filename = <String>::sse_decode(deserializer);
        let mut var_originalSize = <u64>::sse_decode(deserializer);
        let mut var_encryptedSize = <u64>::sse_decode(deserializer);
        let mut var_nonceHex = <String>::sse_decode(deserializer);
        let mut var_schemeVersion = <String>::sse_decode(deserializer);
        let mut var_epoch = <u64>::sse_decode(deserializer);
        return crate::api::EncryptedMediaData {
            encrypted_data: var_encryptedData,
            encrypted_hash_hex: var_encryptedHashHex,
            original_hash_hex: var_originalHashHex,
            mime_type: var_mimeType,
            filename: var_filename,
            original_size: var_originalSize,
            encrypted_size: var_encryptedSize,
            nonce_hex: var_nonceHex,
            scheme_version: var_schemeVersion,
            epoch: var_epoch,
        };
    }
}

impl SseDecode for crate::api::GroupSummaryData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mlsGroupIdHex = <String>::sse_decode(deserializer);
        let mut var_nostrGroupIdHex = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_memberCount = <u32>::sse_decode(deserializer);
        let mut var_adminPubkeysHex = <Vec<String>>::sse_decode(deserializer);
        return crate::api::GroupSummaryData {
            mls_group_id_hex: var_mlsGroupIdHex,
            nostr_group_id_hex: var_nostrGroupIdHex,
            name: var_name,
            description: var_description,
            member_count: var_memberCount,
            admin_pubkeys_hex: var_adminPubkeysHex,
        };
    }
}

impl SseDecode for crate::api::GroupUpdateData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_wrapperEventJson = <String>::sse_decode(deserializer);
        let mut var_wrapperEventIdHex = <String>::sse_decode(deserializer);
        let mut var_mlsGroupIdHex = <String>::sse_decode(deserializer);
        return crate::api::GroupUpdateData {
            wrapper_event_json: var_wrapperEventJson,
            wrapper_event_id_hex: var_wrapperEventIdHex,
            mls_group_id_hex: var_mlsGroupIdHex,
        };
    }
}

impl SseDecode for crate::api::KeyPackageEventData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_tagsJson = <String>::sse_decode(deserializer);
        let mut var_hashRefHex = <String>::sse_decode(deserializer);
        return crate::api::KeyPackageEventData {
            content: var_content,
            tags_json: var_tagsJson,
            hash_ref_hex: var_hashRefHex,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::GroupSummaryData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::GroupSummaryData>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::PendingWelcomeData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::PendingWelcomeData>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::MessageEventData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_wrapperEventJson = <String>::sse_decode(deserializer);
        let mut var_wrapperEventIdHex = <String>::sse_decode(deserializer);
        let mut var_rumorEventIdHex = <String>::sse_decode(deserializer);
        let mut var_mlsGroupIdHex = <String>::sse_decode(deserializer);
        return crate::api::MessageEventData {
            wrapper_event_json: var_wrapperEventJson,
            wrapper_event_id_hex: var_wrapperEventIdHex,
            rumor_event_id_hex: var_rumorEventIdHex,
            mls_group_id_hex: var_mlsGroupIdHex,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::PendingWelcomeData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_welcomeEventIdHex = <String>::sse_decode(deserializer);
        let mut var_wrapperEventIdHex = <String>::sse_decode(deserializer);
        let mut var_mlsGroupIdHex = <String>::sse_decode(deserializer);
        let mut var_nostrGroupIdHex = <String>::sse_decode(deserializer);
        let mut var_groupName = <String>::sse_decode(deserializer);
        let mut var_groupDescription = <String>::sse_decode(deserializer);
        let mut var_memberCount = <u32>::sse_decode(deserializer);
        let mut var_welcomerPubkeyHex = <String>::sse_decode(deserializer);
        let mut var_relays = <Vec<String>>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        return crate::api::PendingWelcomeData {
            welcome_event_id_hex: var_welcomeEventIdHex,
            wrapper_event_id_hex: var_wrapperEventIdHex,
            mls_group_id_hex: var_mlsGroupIdHex,
            nostr_group_id_hex: var_nostrGroupIdHex,
            group_name: var_groupName,
            group_description: var_groupDescription,
            member_count: var_memberCount,
            welcomer_pubkey_hex: var_welcomerPubkeyHex,
            relays: var_relays,
            state: var_state,
        };
    }
}

impl SseDecode for crate::api::ProcessedMessageData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <String>::sse_decode(deserializer);
        let mut var_mlsGroupIdHex = <String>::sse_decode(deserializer);
        let mut var_messageEventIdHex = <String>::sse_decode(deserializer);
        let mut var_wrapperEventIdHex = <String>::sse_decode(deserializer);
        let mut var_pubkeyHex = <String>::sse_decode(deserializer);
        let mut var_kind = <u32>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_createdAt = <u64>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        return crate::api::ProcessedMessageData {
            outcome: var_outcome,
            mls_group_id_hex: var_mlsGroupIdHex,
            message_event_id_hex: var_messageEventIdHex,
            wrapper_event_id_hex: var_wrapperEventIdHex,
            pubkey_hex: var_pubkeyHex,
            kind: var_kind,
            content: var_content,
            created_at: var_createdAt,
            state: var_state,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__accept_pending_welcome_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__bridge_version_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__create_application_message_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__create_key_package_event_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__create_local_group_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__create_local_group_with_welcomes_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__decrypt_media_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__encrypt_media_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__get_group_members_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__get_group_summaries_impl(port, ptr, rust_vec_len, data_len),
        11 => {
            wire__crate__api__get_pending_welcome_summaries_impl(port, ptr, rust_vec_len, data_len)
        }
        12 => wire__crate__api__group_count_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__group_summaries_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__init_mdk_unencrypted_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__leave_group_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__api__mdk_db_path_impl(port, ptr, rust_vec_len, data_len),
        17 => wire__crate__api__process_message_event_impl(port, ptr, rust_vec_len, data_len),
        18 => wire__crate__api__process_welcome_rumor_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__api__remove_group_members_impl(port, ptr, rust_vec_len, data_len),
        20 => wire__crate__api__self_demote_impl(port, ptr, rust_vec_len, data_len),
        21 => wire__crate__api__update_group_admins_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::CreateGroupWithWelcomesData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.group.into_into_dart().into_dart(),
            self.welcome_rumor_jsons.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::CreateGroupWithWelcomesData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::CreateGroupWithWelcomesData>
    for crate::api::CreateGroupWithWelcomesData
{
    fn into_into_dart(self) -> crate::api::CreateGroupWithWelcomesData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::EncryptedMediaData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.encrypted_data.into_into_dart().into_dart(),
            self.encrypted_hash_hex.into_into_dart().into_dart(),
            self.original_hash_hex.into_into_dart().into_dart(),
            self.mime_type.into_into_dart().into_dart(),
            self.filename.into_into_dart().into_dart(),
            self.original_size.into_into_dart().into_dart(),
            self.encrypted_size.into_into_dart().into_dart(),
            self.nonce_hex.into_into_dart().into_dart(),
            self.scheme_version.into_into_dart().into_dart(),
            self.epoch.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::EncryptedMediaData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::EncryptedMediaData>
    for crate::api::EncryptedMediaData
{
    fn into_into_dart(self) -> crate::api::EncryptedMediaData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GroupSummaryData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.mls_group_id_hex.into_into_dart().into_dart(),
            self.nostr_group_id_hex.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.member_count.into_into_dart().into_dart(),
            self.admin_pubkeys_hex.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GroupSummaryData {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GroupSummaryData>
    for crate::api::GroupSummaryData
{
    fn into_into_dart(self) -> crate::api::GroupSummaryData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GroupUpdateData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.wrapper_event_json.into_into_dart().into_dart(),
            self.wrapper_event_id_hex.into_into_dart().into_dart(),
            self.mls_group_id_hex.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GroupUpdateData {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GroupUpdateData>
    for crate::api::GroupUpdateData
{
    fn into_into_dart(self) -> crate::api::GroupUpdateData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::KeyPackageEventData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.content.into_into_dart().into_dart(),
            self.tags_json.into_into_dart().into_dart(),
            self.hash_ref_hex.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::KeyPackageEventData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::KeyPackageEventData>
    for crate::api::KeyPackageEventData
{
    fn into_into_dart(self) -> crate::api::KeyPackageEventData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MessageEventData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.wrapper_event_json.into_into_dart().into_dart(),
            self.wrapper_event_id_hex.into_into_dart().into_dart(),
            self.rumor_event_id_hex.into_into_dart().into_dart(),
            self.mls_group_id_hex.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::MessageEventData {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MessageEventData>
    for crate::api::MessageEventData
{
    fn into_into_dart(self) -> crate::api::MessageEventData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PendingWelcomeData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.welcome_event_id_hex.into_into_dart().into_dart(),
            self.wrapper_event_id_hex.into_into_dart().into_dart(),
            self.mls_group_id_hex.into_into_dart().into_dart(),
            self.nostr_group_id_hex.into_into_dart().into_dart(),
            self.group_name.into_into_dart().into_dart(),
            self.group_description.into_into_dart().into_dart(),
            self.member_count.into_into_dart().into_dart(),
            self.welcomer_pubkey_hex.into_into_dart().into_dart(),
            self.relays.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::PendingWelcomeData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PendingWelcomeData>
    for crate::api::PendingWelcomeData
{
    fn into_into_dart(self) -> crate::api::PendingWelcomeData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ProcessedMessageData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.mls_group_id_hex.into_into_dart().into_dart(),
            self.message_event_id_hex.into_into_dart().into_dart(),
            self.wrapper_event_id_hex.into_into_dart().into_dart(),
            self.pubkey_hex.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ProcessedMessageData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ProcessedMessageData>
    for crate::api::ProcessedMessageData
{
    fn into_into_dart(self) -> crate::api::ProcessedMessageData {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::CreateGroupWithWelcomesData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::GroupSummaryData>::sse_encode(self.group, serializer);
        <Vec<String>>::sse_encode(self.welcome_rumor_jsons, serializer);
    }
}

impl SseEncode for crate::api::EncryptedMediaData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.encrypted_data, serializer);
        <String>::sse_encode(self.encrypted_hash_hex, serializer);
        <String>::sse_encode(self.original_hash_hex, serializer);
        <String>::sse_encode(self.mime_type, serializer);
        <String>::sse_encode(self.filename, serializer);
        <u64>::sse_encode(self.original_size, serializer);
        <u64>::sse_encode(self.encrypted_size, serializer);
        <String>::sse_encode(self.nonce_hex, serializer);
        <String>::sse_encode(self.scheme_version, serializer);
        <u64>::sse_encode(self.epoch, serializer);
    }
}

impl SseEncode for crate::api::GroupSummaryData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.mls_group_id_hex, serializer);
        <String>::sse_encode(self.nostr_group_id_hex, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.description, serializer);
        <u32>::sse_encode(self.member_count, serializer);
        <Vec<String>>::sse_encode(self.admin_pubkeys_hex, serializer);
    }
}

impl SseEncode for crate::api::GroupUpdateData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.wrapper_event_json, serializer);
        <String>::sse_encode(self.wrapper_event_id_hex, serializer);
        <String>::sse_encode(self.mls_group_id_hex, serializer);
    }
}

impl SseEncode for crate::api::KeyPackageEventData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.content, serializer);
        <String>::sse_encode(self.tags_json, serializer);
        <String>::sse_encode(self.hash_ref_hex, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::GroupSummaryData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::GroupSummaryData>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::PendingWelcomeData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::PendingWelcomeData>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::MessageEventData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.wrapper_event_json, serializer);
        <String>::sse_encode(self.wrapper_event_id_hex, serializer);
        <String>::sse_encode(self.rumor_event_id_hex, serializer);
        <String>::sse_encode(self.mls_group_id_hex, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::PendingWelcomeData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.welcome_event_id_hex, serializer);
        <String>::sse_encode(self.wrapper_event_id_hex, serializer);
        <String>::sse_encode(self.mls_group_id_hex, serializer);
        <String>::sse_encode(self.nostr_group_id_hex, serializer);
        <String>::sse_encode(self.group_name, serializer);
        <String>::sse_encode(self.group_description, serializer);
        <u32>::sse_encode(self.member_count, serializer);
        <String>::sse_encode(self.welcomer_pubkey_hex, serializer);
        <Vec<String>>::sse_encode(self.relays, serializer);
        <String>::sse_encode(self.state, serializer);
    }
}

impl SseEncode for crate::api::ProcessedMessageData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.outcome, serializer);
        <String>::sse_encode(self.mls_group_id_hex, serializer);
        <String>::sse_encode(self.message_event_id_hex, serializer);
        <String>::sse_encode(self.wrapper_event_id_hex, serializer);
        <String>::sse_encode(self.pubkey_hex, serializer);
        <u32>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.content, serializer);
        <u64>::sse_encode(self.created_at, serializer);
        <String>::sse_encode(self.state, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
