import 'package:flutter/material.dart';

import 'ar_filter_catalog.dart';

class GeneratedArFilterCatalog {
  const GeneratedArFilterCatalog._();

  static const communityFilters = <ArFilterDefinition>[
    ArFilterDefinition(
      id: "studio-pup-pop",
      label: "Pup Pop",
      category: "Animal",
      description: "Warm puppy ears, nose, and tongue.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-pup-pop_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.36,
          offset: Offset(-0.34, -0.54),
          rotationDegrees: -12.0,
          opacity: 1.0,
          blossomHash: "57dc7e78bca6a0ca1056db2dfe6d1354adc6a4ecc56503f2dc70708e4e523404",
          byteLength: 15351,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-pup-pop_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.36,
          offset: Offset(0.34, -0.54),
          rotationDegrees: 12.0,
          opacity: 1.0,
          blossomHash: "f402c67d01130aa82ff00eeb9f02fcce2c33d5c2656869a111b9e62de27ccbc5",
          byteLength: 15280,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-pup-pop_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.24,
          offset: Offset(0.0, 0.03),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "a5a30dfebc1008fdf5a9e49ce1e696885f3b0adb36c2d8a39a0d889d4c335a16",
          byteLength: 7831,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-pup-pop_04.png",
          anchor: ArFilterAnchor.mouthCenter,
          widthScale: 0.22,
          offset: Offset(0.0, 0.22),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "aa531bdf1a0b6bd1fd70a77e6f69c048b66b54a755886dcb9b28053ac62cd7ec",
          byteLength: 11283,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-pup-cream",
      label: "Cream Pup",
      category: "Animal",
      description: "Soft cream ears with a glossy nose.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-pup-cream_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.38,
          offset: Offset(-0.35, -0.56),
          rotationDegrees: -11.0,
          opacity: 1.0,
          blossomHash: "547cdce0af5c72853e7e6f0bb40e502a2a67a0bdb42f4b820fb0cb9e38e36d06",
          byteLength: 14139,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-pup-cream_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.38,
          offset: Offset(0.35, -0.56),
          rotationDegrees: 11.0,
          opacity: 1.0,
          blossomHash: "50bc4ea4990485f697229a9767c38bd254500291d0a732fab8d8156b1de7f9bf",
          byteLength: 13911,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-pup-cream_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.22,
          offset: Offset(0.0, 0.02),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "a5a30dfebc1008fdf5a9e49ce1e696885f3b0adb36c2d8a39a0d889d4c335a16",
          byteLength: 7831,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-cat-noir",
      label: "Cat Noir",
      category: "Animal",
      description: "Black cat ears, nose, and crisp whiskers.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-cat-noir_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.34,
          offset: Offset(-0.34, -0.58),
          rotationDegrees: -9.0,
          opacity: 1.0,
          blossomHash: "2d2af8a240d2d8d593e6dfc33fe249095c3f242e8a282b53f6d1220a9865e0cd",
          byteLength: 14634,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-cat-noir_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.34,
          offset: Offset(0.34, -0.58),
          rotationDegrees: 9.0,
          opacity: 1.0,
          blossomHash: "889ce25c607b7bdd1d1b897126dcf781ef8631050c0d5602894f332b768d762d",
          byteLength: 14720,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-cat-noir_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.16,
          offset: Offset(0.0, 0.03),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "2627bb992121cd3ab41acf6247dee5d6d5b42fd6062caf84548e9f8f78016273",
          byteLength: 8923,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-cat-noir_04.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.74,
          offset: Offset(0.0, 0.08),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "1d3e1e7fef654dd54fc29dd975c28c5ad273cff2b67fa069093a9e6e89051237",
          byteLength: 12558,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-cat-pink",
      label: "Pink Cat",
      category: "Animal",
      description: "Pink-lined ears and soft whiskers.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-cat-pink_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.34,
          offset: Offset(-0.34, -0.58),
          rotationDegrees: -9.0,
          opacity: 1.0,
          blossomHash: "dff9c032ad8233a365a47629b3181ec6ef8b2c9a1458984f98b5da0b08039d9d",
          byteLength: 14491,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-cat-pink_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.34,
          offset: Offset(0.34, -0.58),
          rotationDegrees: 9.0,
          opacity: 1.0,
          blossomHash: "d22f9e0b1cb252a4fcbe08fd7ec48630a10a0f452bbcc1e52ff9d50a32752ec5",
          byteLength: 14528,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-cat-pink_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.16,
          offset: Offset(0.0, 0.03),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "90697ab0e423b3a5e50bfa5ad107edee38822d5ec4aae99849959b2a7fdf11ac",
          byteLength: 8882,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-cat-pink_04.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.74,
          offset: Offset(0.0, 0.08),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "73673656959641aebc362dd0527a01298e13cff1d4c5d60ff76faf16fad02117",
          byteLength: 12937,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-fox-flare",
      label: "Fox Flare",
      category: "Animal",
      description: "Orange fox ears with a tiny nose.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-fox-flare_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.38,
          offset: Offset(-0.36, -0.57),
          rotationDegrees: -10.0,
          opacity: 1.0,
          blossomHash: "58fa07851cabc5a704badf1084c08f7e8601b13890bff967a276ea0967139d23",
          byteLength: 14462,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-fox-flare_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.38,
          offset: Offset(0.36, -0.57),
          rotationDegrees: 10.0,
          opacity: 1.0,
          blossomHash: "a3f0d258f746f86fa58258d928405c237b5913d604476635f3e672bfe77d5b48",
          byteLength: 14590,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-fox-flare_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.18,
          offset: Offset(0.0, 0.03),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "36eda11ab03bd9343f20eef326afcfe9a1f2c0f2cd4c7a4bdc0fb5cae0f817eb",
          byteLength: 7790,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-bunny-cloud",
      label: "Bunny Cloud",
      category: "Animal",
      description: "Tall plush ears and a soft nose.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-bunny-cloud_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.32,
          offset: Offset(-0.27, -0.72),
          rotationDegrees: -7.0,
          opacity: 1.0,
          blossomHash: "ec3aa0b801571c1506af48d7d5dc6f5dd2864095e01a806cc2f018b593c0b0cd",
          byteLength: 14862,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-bunny-cloud_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.32,
          offset: Offset(0.27, -0.72),
          rotationDegrees: 7.0,
          opacity: 1.0,
          blossomHash: "2513a646868a7c6cd6e2ca298c6da7c5c358b93f5b665ea8689410f434a963bb",
          byteLength: 14941,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-bunny-cloud_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.13,
          offset: Offset(0.0, 0.03),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "cb6f993a3eeabf4d7618bd7cafeba74bb46b71930112a9e6e75ea3d87b080303",
          byteLength: 8834,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-bear-plush",
      label: "Bear Plush",
      category: "Animal",
      description: "Rounded plush ears and nose.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-bear-plush_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.26,
          offset: Offset(-0.34, -0.48),
          rotationDegrees: -4.0,
          opacity: 1.0,
          blossomHash: "5e709b9bf3dd16d3c9b4ff13d36b018b15e5802f8b5ce90ee8f2712ed8a7a437",
          byteLength: 18420,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-bear-plush_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.26,
          offset: Offset(0.34, -0.48),
          rotationDegrees: 4.0,
          opacity: 1.0,
          blossomHash: "5e709b9bf3dd16d3c9b4ff13d36b018b15e5802f8b5ce90ee8f2712ed8a7a437",
          byteLength: 18420,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-bear-plush_03.png",
          anchor: ArFilterAnchor.noseTip,
          widthScale: 0.2,
          offset: Offset(0.0, 0.04),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "7d76245091f91083d0ae2539c148f02c792a051a2863bff5cc4afb8d1821b08e",
          byteLength: 7926,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-antler-glow",
      label: "Antler Glow",
      category: "Headwear",
      description: "Light antlers with tiny shine accents.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-antler-glow_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 1.08,
          offset: Offset(0.0, -0.57),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "d49782ae5d2369e4e894c1848fadb4236e4d6dba6df43a7f55373b2ac475920b",
          byteLength: 18229,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-devil-gloss",
      label: "Gloss Horns",
      category: "Headwear",
      description: "Glossy red horns with a subtle highlight.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-devil-gloss_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.3,
          offset: Offset(-0.34, -0.5),
          rotationDegrees: -5.0,
          opacity: 1.0,
          blossomHash: "2b1603f76d23f1e0597e337719cee1a76b7135fe133f36e7f3ff9c5b5d118239",
          byteLength: 14520,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-devil-gloss_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.3,
          offset: Offset(0.34, -0.5),
          rotationDegrees: 5.0,
          opacity: 1.0,
          blossomHash: "409ec9bb77cd85bb891fa060d68684ceb789b40c7bd6c30386a30bcf9ef9df9b",
          byteLength: 14739,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-halo",
      label: "Halo",
      category: "Headwear",
      description: "Soft golden halo.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-halo_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.72,
          offset: Offset(0.0, -0.64),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "36d00c1f9026b825b42b8dd16bc3ddcd7cb0891d600108a4669263e09a8147fb",
          byteLength: 24477,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-flower-crown",
      label: "Flower Crown",
      category: "Headwear",
      description: "Layered flowers and leaves.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-flower-crown_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 1.02,
          offset: Offset(0.0, -0.5),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "de15a6e6a67aa1092e5d74cf7c464384ca33f3a050f131eb5ea3a287f502ee1a",
          byteLength: 19731,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-tropical-crown",
      label: "Tropical Crown",
      category: "Headwear",
      description: "Bright flowers with green leaves.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-tropical-crown_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 1.02,
          offset: Offset(0.0, -0.5),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "8788190394abb9751c00b2aa68ab8f3d5c148d0bd8e6d004f47f78ee299d3d24",
          byteLength: 20068,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-gold-crown",
      label: "Gold Crown",
      category: "Headwear",
      description: "Polished crown with jewel accents.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-gold-crown_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.84,
          offset: Offset(0.0, -0.55),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "1ee5187ae52e2fd15e1e9081857d065826bc83a0b052503b1daf6879901b5a27",
          byteLength: 12414,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-crystal-tiara",
      label: "Crystal Tiara",
      category: "Headwear",
      description: "Clean crystal tiara.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-crystal-tiara_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.8,
          offset: Offset(0.0, -0.48),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "509f04b268091863188ac850c95b1b05bf1c6a2f723e38eac3083efc4264642c",
          byteLength: 14929,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-cowboy",
      label: "Cowboy",
      category: "Headwear",
      description: "Clean western hat silhouette.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-cowboy_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.98,
          offset: Offset(0.0, -0.52),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "c8e424f77f535d121af4da807b9f16ab3a6459c7ba15ad72db9999b7647a00c2",
          byteLength: 14688,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-witch",
      label: "Witch",
      category: "Headwear",
      description: "Tall purple hat with a moon pin.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-witch_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.86,
          offset: Offset(0.0, -0.67),
          rotationDegrees: -5.0,
          opacity: 1.0,
          blossomHash: "77d31043e52d7aa67f1150a77a785c83685781172b0d7f514075a32f5c59bf50",
          byteLength: 11636,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-wizard",
      label: "Wizard",
      category: "Headwear",
      description: "Blue starry wizard hat.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-wizard_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.86,
          offset: Offset(0.0, -0.68),
          rotationDegrees: 5.0,
          opacity: 1.0,
          blossomHash: "aace302e94f60b8c5390f3a4197c8f2eb746047366fdd4dba8aec8f8cec51c49",
          byteLength: 13685,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-star-shades",
      label: "Star Shades",
      category: "Eyewear",
      description: "Bold star sunglasses.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-star-shades_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.02,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "8e9a65aec2539b0dcd4af911c148d1a23d186c7790cd639eb1fb48a2dee7a417",
          byteLength: 7027,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-heart-shades",
      label: "Heart Shades",
      category: "Eyewear",
      description: "Pink heart sunglasses.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-heart-shades_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.02,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "9dced7f2e15ab7ba8c997168e8f3aa654d2a0b636e441b9d466195154300decb",
          byteLength: 11299,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-chrome-shades",
      label: "Chrome Shades",
      category: "Eyewear",
      description: "Reflective visor-style shades.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-chrome-shades_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.08,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "fa2a3202f6a4115934ebc664245910e9a88d7e35ca41e27912637a8ebdf7eb7e",
          byteLength: 13814,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-neon-visor",
      label: "Neon Visor",
      category: "Eyewear",
      description: "Cyber visor with cyan and magenta accents.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-neon-visor_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.12,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "d77338f5f9073a83bdadf2e477a1fc32b800bf2531b695615a02b9aa4fd51f26",
          byteLength: 14037,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-retro-glasses",
      label: "Retro Glasses",
      category: "Eyewear",
      description: "Chunky retro frames.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-retro-glasses_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.02,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "a674762e5d0dbfb2c9ddd1d7bc5ddf167445df3969f1b02677c4b943efabfa21",
          byteLength: 6900,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-round-glasses",
      label: "Round Glasses",
      category: "Eyewear",
      description: "Wire round glasses with sparkle.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-round-glasses_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 0.92,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "a29c24ca864ddc8c4075d0d0cb233ddb86cf8c07c18f319c9d30e9d8e546da20",
          byteLength: 13519,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-round-glasses_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.22,
          offset: Offset(0.42, -0.36),
          rotationDegrees: 15.0,
          opacity: 1.0,
          blossomHash: "37e1c4c16258b6eeb89994beb232f04d2ae1c0770a8e8d25e33705f27c67ed20",
          byteLength: 12741,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-butterfly-mask",
      label: "Butterfly Mask",
      category: "Masks",
      description: "Butterfly mask with layered color.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-butterfly-mask_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.16,
          offset: Offset(0.0, 0.02),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "8e7ce503f0af5bf15387b85d34cf8aed608453393d2045346d8416f8ff81df31",
          byteLength: 17370,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-gold-mask",
      label: "Gold Mask",
      category: "Masks",
      description: "Masquerade mask with gold trim.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-gold-mask_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.12,
          offset: Offset(0.0, 0.02),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "54ba660d0d9f8f6c8a0d6778990a9099ba2d69cea4280291ff345a0713af3c24",
          byteLength: 16192,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-cyber-mask",
      label: "Cyber Mask",
      category: "Masks",
      description: "Angular chrome half mask.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-cyber-mask_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.08,
          offset: Offset(0.0, 0.04),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "3eb79d67a3b8b31afac327feacda77a8336f6eee8a921098191f7ad2ec4eff7c",
          byteLength: 10200,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-glitter-freckles",
      label: "Glitter Freckles",
      category: "Effects",
      description: "Tiny stars around the cheeks.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-glitter-freckles_01.png",
          anchor: ArFilterAnchor.leftEye,
          widthScale: 0.32,
          offset: Offset(-0.06, 0.28),
          rotationDegrees: -8.0,
          opacity: 1.0,
          blossomHash: "9974a95ac153e002b4743595aaaf5e1a1e80f2c9ec5d64723d44f14a7e7f7353",
          byteLength: 5829,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-glitter-freckles_02.png",
          anchor: ArFilterAnchor.rightEye,
          widthScale: 0.32,
          offset: Offset(0.06, 0.28),
          rotationDegrees: 8.0,
          opacity: 1.0,
          blossomHash: "139d061ebaed429a77a51e46b56879877d89c3d86c691fa68408fcd37c9b4f9a",
          byteLength: 5902,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-heart-blush",
      label: "Heart Blush",
      category: "Effects",
      description: "Small heart blush marks.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-heart-blush_01.png",
          anchor: ArFilterAnchor.leftEye,
          widthScale: 0.25,
          offset: Offset(-0.1, 0.32),
          rotationDegrees: -8.0,
          opacity: 1.0,
          blossomHash: "d110617e85a198073d2928f5d52f2125b1c3cf304f49efeba1307d3ed413f245",
          byteLength: 10004,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-heart-blush_02.png",
          anchor: ArFilterAnchor.rightEye,
          widthScale: 0.25,
          offset: Offset(0.1, 0.32),
          rotationDegrees: 8.0,
          opacity: 1.0,
          blossomHash: "d110617e85a198073d2928f5d52f2125b1c3cf304f49efeba1307d3ed413f245",
          byteLength: 10004,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-creator-spark",
      label: "Creator Spark",
      category: "Effects",
      description: "Asymmetric sparkle accents.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-creator-spark_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.42,
          offset: Offset(-0.42, -0.42),
          rotationDegrees: -12.0,
          opacity: 1.0,
          blossomHash: "a852edc2c2058b7a9cef0f9bcda34fe7aaf2128ce55c138eb2c7cee1f2f1f9e5",
          byteLength: 12696,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-creator-spark_02.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.24,
          offset: Offset(0.42, -0.32),
          rotationDegrees: 18.0,
          opacity: 1.0,
          blossomHash: "37e1c4c16258b6eeb89994beb232f04d2ae1c0770a8e8d25e33705f27c67ed20",
          byteLength: 12741,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-star-dust",
      label: "Star Dust",
      category: "Effects",
      description: "Soft star accents across the forehead.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-star-dust_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.96,
          offset: Offset(0.0, -0.46),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "ff6684346df3b9d67335d271e6001020e27a32cf3fd810f35bc49b30f73d8e04",
          byteLength: 11744,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-lightning",
      label: "Lightning",
      category: "Effects",
      description: "Graphic lightning cheek marks.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-lightning_01.png",
          anchor: ArFilterAnchor.leftEye,
          widthScale: 0.28,
          offset: Offset(-0.1, 0.32),
          rotationDegrees: -8.0,
          opacity: 1.0,
          blossomHash: "e0dc15e44fe4403167013e4cd83505550a3259f0a9ea6ef2853a66328a13662b",
          byteLength: 13965,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-lightning_02.png",
          anchor: ArFilterAnchor.rightEye,
          widthScale: 0.28,
          offset: Offset(0.1, 0.32),
          rotationDegrees: 8.0,
          opacity: 1.0,
          blossomHash: "c4039f37c5476f25ac389260956cbe9258670d2a567094b8fce8d33d7acbc168",
          byteLength: 14016,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-headphones",
      label: "Headphones",
      category: "Creator",
      description: "Bright streamer headphones.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-headphones_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.16,
          offset: Offset(0.0, -0.21),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "4819c28aa6b866156dc99bdd93574b357cea1f30a9dc15059d5905d9c8f8267a",
          byteLength: 15884,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-monocle-stache",
      label: "Monocle Stache",
      category: "Creator",
      description: "Monocle and curled mustache.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-monocle-stache_01.png",
          anchor: ArFilterAnchor.rightEye,
          widthScale: 0.36,
          offset: Offset(0.0, 0.02),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "2fd1ffa11110e329f595af9629e584555169b01485d1dbee301c55e3fa07099a",
          byteLength: 21112,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-monocle-stache_02.png",
          anchor: ArFilterAnchor.mouthCenter,
          widthScale: 0.58,
          offset: Offset(0.0, -0.12),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "e28a9ba61d458ee77c4ad1d5e1c5ca67d3ed1aa7e0ef1f3944d855404c562d9c",
          byteLength: 11655,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-comic-stache",
      label: "Comic Stache",
      category: "Creator",
      description: "Big curled mustache and bow tie.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-comic-stache_01.png",
          anchor: ArFilterAnchor.mouthCenter,
          widthScale: 0.64,
          offset: Offset(0.0, -0.12),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "e28a9ba61d458ee77c4ad1d5e1c5ca67d3ed1aa7e0ef1f3944d855404c562d9c",
          byteLength: 11655,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-comic-stache_02.png",
          anchor: ArFilterAnchor.mouthCenter,
          widthScale: 0.52,
          offset: Offset(0.0, 0.5),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "7962e3eb01cb2f23e0e550d17833825febe80e8938ea4f4228af4d0665358f7b",
          byteLength: 10886,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-bow-shades",
      label: "Bow Shades",
      category: "Creator",
      description: "Dark shades and a bright bow tie.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-bow-shades_01.png",
          anchor: ArFilterAnchor.eyesBridge,
          widthScale: 1.02,
          offset: Offset(0.0, 0.0),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "fa2a3202f6a4115934ebc664245910e9a88d7e35ca41e27912637a8ebdf7eb7e",
          byteLength: 13814,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
        ArFilterPartDefinition(
          assetPath: "studio-bow-shades_02.png",
          anchor: ArFilterAnchor.mouthCenter,
          widthScale: 0.52,
          offset: Offset(0.0, 0.5),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "7962e3eb01cb2f23e0e550d17833825febe80e8938ea4f4228af4d0665358f7b",
          byteLength: 10886,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
    ArFilterDefinition(
      id: "studio-laurel",
      label: "Laurel",
      category: "Headwear",
      description: "Clean laurel crown.",
      sourceName: "Tubestr Studio AR Filter Pack",
      sourceUrl: "scripts/generate_ar_filter_studio_pack.py",
      license: "MIT",
      licenseUrl: "https://opensource.org/license/mit",
      attribution: "Tubestr original vector AR assets.",
      parts: <ArFilterPartDefinition>[
        ArFilterPartDefinition(
          assetPath: "studio-laurel_01.png",
          anchor: ArFilterAnchor.forehead,
          widthScale: 0.9,
          offset: Offset(0.0, -0.48),
          rotationDegrees: 0.0,
          opacity: 1.0,
          blossomHash: "058d8bb5a386901e098827e12ad59675a81b72f5f73e9562be3784792c2975ce",
          byteLength: 15558,
          mimeType: "image/png",
          blossomServers: <String>[
            "https://blossom.tubestr.app",
          ],
        ),
      ],
    ),
  ];
}
