// Generated by scripts/import_fluent_stickers.py. Do not edit by hand.

import '../../domain/models/editor_resources.dart';

class GeneratedStickerCatalog {
  const GeneratedStickerCatalog._();

  static const fluentEmojiStickerAssets = <EditorStickerAsset>[
    EditorStickerAsset(
      id: 'fluent_emoji_grinning_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_grinning_face.png',
      label: 'Grinning face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_grinning_face_with_big_eyes',
      assetPath:
          'assets/editor/stickers/fluent_emoji_grinning_face_with_big_eyes.png',
      label: 'Grinning face with big eyes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_grinning_face_with_smiling_eyes',
      assetPath:
          'assets/editor/stickers/fluent_emoji_grinning_face_with_smiling_eyes.png',
      label: 'Grinning face with smiling eyes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_beaming_face_with_smiling_eyes',
      assetPath:
          'assets/editor/stickers/fluent_emoji_beaming_face_with_smiling_eyes.png',
      label: 'Beaming face with smiling eyes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_grinning_squinting_face',
      assetPath:
          'assets/editor/stickers/fluent_emoji_grinning_squinting_face.png',
      label: 'Grinning squinting face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_rolling_on_the_floor_laughing',
      assetPath:
          'assets/editor/stickers/fluent_emoji_rolling_on_the_floor_laughing.png',
      label: 'Rolling on the floor laughing',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_with_tears_of_joy',
      assetPath:
          'assets/editor/stickers/fluent_emoji_face_with_tears_of_joy.png',
      label: 'Face with tears of joy',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_slightly_smiling_face',
      assetPath:
          'assets/editor/stickers/fluent_emoji_slightly_smiling_face.png',
      label: 'Slightly smiling face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_upside_down_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_upside_down_face.png',
      label: 'Upside-down face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_winking_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_winking_face.png',
      label: 'Winking face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_smiling_face_with_smiling_eyes',
      assetPath:
          'assets/editor/stickers/fluent_emoji_smiling_face_with_smiling_eyes.png',
      label: 'Smiling face with smiling eyes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_smiling_face_with_halo',
      assetPath:
          'assets/editor/stickers/fluent_emoji_smiling_face_with_halo.png',
      label: 'Smiling face with halo',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_smiling_face_with_hearts',
      assetPath:
          'assets/editor/stickers/fluent_emoji_smiling_face_with_hearts.png',
      label: 'Smiling face with hearts',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_smiling_face_with_heart_eyes',
      assetPath:
          'assets/editor/stickers/fluent_emoji_smiling_face_with_heart_eyes.png',
      label: 'Smiling face with heart-eyes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_star_struck',
      assetPath: 'assets/editor/stickers/fluent_emoji_star_struck.png',
      label: 'Star-struck',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_blowing_a_kiss',
      assetPath: 'assets/editor/stickers/fluent_emoji_face_blowing_a_kiss.png',
      label: 'Face blowing a kiss',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_kissing_face_with_closed_eyes',
      assetPath:
          'assets/editor/stickers/fluent_emoji_kissing_face_with_closed_eyes.png',
      label: 'Kissing face with closed eyes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_smiling_face_with_tear',
      assetPath:
          'assets/editor/stickers/fluent_emoji_smiling_face_with_tear.png',
      label: 'Smiling face with tear',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_savoring_food',
      assetPath: 'assets/editor/stickers/fluent_emoji_face_savoring_food.png',
      label: 'Face savoring food',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_with_tongue',
      assetPath: 'assets/editor/stickers/fluent_emoji_face_with_tongue.png',
      label: 'Face with tongue',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_zany_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_zany_face.png',
      label: 'Zany face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_squinting_face_with_tongue',
      assetPath:
          'assets/editor/stickers/fluent_emoji_squinting_face_with_tongue.png',
      label: 'Squinting face with tongue',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_money_mouth_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_money_mouth_face.png',
      label: 'Money-mouth face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_smiling_face_with_sunglasses',
      assetPath:
          'assets/editor/stickers/fluent_emoji_smiling_face_with_sunglasses.png',
      label: 'Smiling face with sunglasses',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_nerd_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_nerd_face.png',
      label: 'Nerd face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_with_monocle',
      assetPath: 'assets/editor/stickers/fluent_emoji_face_with_monocle.png',
      label: 'Face with monocle',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_partying_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_partying_face.png',
      label: 'Partying face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cowboy_hat_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_cowboy_hat_face.png',
      label: 'Cowboy hat face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_clown_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_clown_face.png',
      label: 'Clown face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_ghost',
      assetPath: 'assets/editor/stickers/fluent_emoji_ghost.png',
      label: 'Ghost',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_alien',
      assetPath: 'assets/editor/stickers/fluent_emoji_alien.png',
      label: 'Alien',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_robot',
      assetPath: 'assets/editor/stickers/fluent_emoji_robot.png',
      label: 'Robot',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_thinking_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_thinking_face.png',
      label: 'Thinking face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_shushing_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_shushing_face.png',
      label: 'Shushing face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_with_hand_over_mouth',
      assetPath:
          'assets/editor/stickers/fluent_emoji_face_with_hand_over_mouth.png',
      label: 'Face with hand over mouth',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_saluting_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_saluting_face.png',
      label: 'Saluting face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_melting_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_melting_face.png',
      label: 'Melting face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_exploding_head',
      assetPath: 'assets/editor/stickers/fluent_emoji_exploding_head.png',
      label: 'Exploding head',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_flushed_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_flushed_face.png',
      label: 'Flushed face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_pleading_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_pleading_face.png',
      label: 'Pleading face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_face_screaming_in_fear',
      assetPath:
          'assets/editor/stickers/fluent_emoji_face_screaming_in_fear.png',
      label: 'Face screaming in fear',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_red_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_red_heart.png',
      label: 'Red heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_orange_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_orange_heart.png',
      label: 'Orange heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_yellow_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_yellow_heart.png',
      label: 'Yellow heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_green_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_green_heart.png',
      label: 'Green heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_blue_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_blue_heart.png',
      label: 'Blue heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_purple_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_purple_heart.png',
      label: 'Purple heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_white_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_white_heart.png',
      label: 'White heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_sparkling_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_sparkling_heart.png',
      label: 'Sparkling heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_heart_with_arrow',
      assetPath: 'assets/editor/stickers/fluent_emoji_heart_with_arrow.png',
      label: 'Heart with arrow',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_heart_with_ribbon',
      assetPath: 'assets/editor/stickers/fluent_emoji_heart_with_ribbon.png',
      label: 'Heart with ribbon',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_growing_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_growing_heart.png',
      label: 'Growing heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_beating_heart',
      assetPath: 'assets/editor/stickers/fluent_emoji_beating_heart.png',
      label: 'Beating heart',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_revolving_hearts',
      assetPath: 'assets/editor/stickers/fluent_emoji_revolving_hearts.png',
      label: 'Revolving hearts',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_two_hearts',
      assetPath: 'assets/editor/stickers/fluent_emoji_two_hearts.png',
      label: 'Two hearts',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_heart_on_fire',
      assetPath: 'assets/editor/stickers/fluent_emoji_heart_on_fire.png',
      label: 'Heart on fire',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_hundred_points',
      assetPath: 'assets/editor/stickers/fluent_emoji_hundred_points.png',
      label: 'Hundred points',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_collision',
      assetPath: 'assets/editor/stickers/fluent_emoji_collision.png',
      label: 'Collision',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_dizzy',
      assetPath: 'assets/editor/stickers/fluent_emoji_dizzy.png',
      label: 'Dizzy',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_dashing_away',
      assetPath: 'assets/editor/stickers/fluent_emoji_dashing_away.png',
      label: 'Dashing away',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_party_popper',
      assetPath: 'assets/editor/stickers/fluent_emoji_party_popper.png',
      label: 'Party popper',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_confetti_ball',
      assetPath: 'assets/editor/stickers/fluent_emoji_confetti_ball.png',
      label: 'Confetti ball',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_balloon',
      assetPath: 'assets/editor/stickers/fluent_emoji_balloon.png',
      label: 'Balloon',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_wrapped_gift',
      assetPath: 'assets/editor/stickers/fluent_emoji_wrapped_gift.png',
      label: 'Wrapped gift',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_birthday_cake',
      assetPath: 'assets/editor/stickers/fluent_emoji_birthday_cake.png',
      label: 'Birthday cake',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_sparkles',
      assetPath: 'assets/editor/stickers/fluent_emoji_sparkles.png',
      label: 'Sparkles',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_glowing_star',
      assetPath: 'assets/editor/stickers/fluent_emoji_glowing_star.png',
      label: 'Glowing star',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_star',
      assetPath: 'assets/editor/stickers/fluent_emoji_star.png',
      label: 'Star',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_rainbow',
      assetPath: 'assets/editor/stickers/fluent_emoji_rainbow.png',
      label: 'Rainbow',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_fire',
      assetPath: 'assets/editor/stickers/fluent_emoji_fire.png',
      label: 'Fire',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_high_voltage',
      assetPath: 'assets/editor/stickers/fluent_emoji_high_voltage.png',
      label: 'High voltage',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_trophy',
      assetPath: 'assets/editor/stickers/fluent_emoji_trophy.png',
      label: 'Trophy',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_sports_medal',
      assetPath: 'assets/editor/stickers/fluent_emoji_sports_medal.png',
      label: 'Sports medal',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_1st_place_medal',
      assetPath: 'assets/editor/stickers/fluent_emoji_1st_place_medal.png',
      label: '1st place medal',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_2nd_place_medal',
      assetPath: 'assets/editor/stickers/fluent_emoji_2nd_place_medal.png',
      label: '2nd place medal',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_3rd_place_medal',
      assetPath: 'assets/editor/stickers/fluent_emoji_3rd_place_medal.png',
      label: '3rd place medal',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_soccer_ball',
      assetPath: 'assets/editor/stickers/fluent_emoji_soccer_ball.png',
      label: 'Soccer ball',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_basketball',
      assetPath: 'assets/editor/stickers/fluent_emoji_basketball.png',
      label: 'Basketball',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_baseball',
      assetPath: 'assets/editor/stickers/fluent_emoji_baseball.png',
      label: 'Baseball',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_softball',
      assetPath: 'assets/editor/stickers/fluent_emoji_softball.png',
      label: 'Softball',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_tennis',
      assetPath: 'assets/editor/stickers/fluent_emoji_tennis.png',
      label: 'Tennis',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_volleyball',
      assetPath: 'assets/editor/stickers/fluent_emoji_volleyball.png',
      label: 'Volleyball',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_flying_disc',
      assetPath: 'assets/editor/stickers/fluent_emoji_flying_disc.png',
      label: 'Flying disc',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_kite',
      assetPath: 'assets/editor/stickers/fluent_emoji_kite.png',
      label: 'Kite',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_yo_yo',
      assetPath: 'assets/editor/stickers/fluent_emoji_yo_yo.png',
      label: 'Yo-yo',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_magic_wand',
      assetPath: 'assets/editor/stickers/fluent_emoji_magic_wand.png',
      label: 'Magic wand',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_video_game',
      assetPath: 'assets/editor/stickers/fluent_emoji_video_game.png',
      label: 'Video game',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_joystick',
      assetPath: 'assets/editor/stickers/fluent_emoji_joystick.png',
      label: 'Joystick',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_artist_palette',
      assetPath: 'assets/editor/stickers/fluent_emoji_artist_palette.png',
      label: 'Artist palette',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_musical_notes',
      assetPath: 'assets/editor/stickers/fluent_emoji_musical_notes.png',
      label: 'Musical notes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_microphone',
      assetPath: 'assets/editor/stickers/fluent_emoji_microphone.png',
      label: 'Microphone',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_headphone',
      assetPath: 'assets/editor/stickers/fluent_emoji_headphone.png',
      label: 'Headphone',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_guitar',
      assetPath: 'assets/editor/stickers/fluent_emoji_guitar.png',
      label: 'Guitar',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_drum',
      assetPath: 'assets/editor/stickers/fluent_emoji_drum.png',
      label: 'Drum',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_trumpet',
      assetPath: 'assets/editor/stickers/fluent_emoji_trumpet.png',
      label: 'Trumpet',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_violin',
      assetPath: 'assets/editor/stickers/fluent_emoji_violin.png',
      label: 'Violin',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_dog_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_dog_face.png',
      label: 'Dog face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cat_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_cat_face.png',
      label: 'Cat face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_mouse_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_mouse_face.png',
      label: 'Mouse face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_hamster',
      assetPath: 'assets/editor/stickers/fluent_emoji_hamster.png',
      label: 'Hamster',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_rabbit_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_rabbit_face.png',
      label: 'Rabbit face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_fox',
      assetPath: 'assets/editor/stickers/fluent_emoji_fox.png',
      label: 'Fox',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_bear',
      assetPath: 'assets/editor/stickers/fluent_emoji_bear.png',
      label: 'Bear',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_panda',
      assetPath: 'assets/editor/stickers/fluent_emoji_panda.png',
      label: 'Panda',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_koala',
      assetPath: 'assets/editor/stickers/fluent_emoji_koala.png',
      label: 'Koala',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_tiger_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_tiger_face.png',
      label: 'Tiger face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_lion',
      assetPath: 'assets/editor/stickers/fluent_emoji_lion.png',
      label: 'Lion',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cow_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_cow_face.png',
      label: 'Cow face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_pig_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_pig_face.png',
      label: 'Pig face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_frog',
      assetPath: 'assets/editor/stickers/fluent_emoji_frog.png',
      label: 'Frog',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_monkey_face',
      assetPath: 'assets/editor/stickers/fluent_emoji_monkey_face.png',
      label: 'Monkey face',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_chicken',
      assetPath: 'assets/editor/stickers/fluent_emoji_chicken.png',
      label: 'Chicken',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_penguin',
      assetPath: 'assets/editor/stickers/fluent_emoji_penguin.png',
      label: 'Penguin',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_bird',
      assetPath: 'assets/editor/stickers/fluent_emoji_bird.png',
      label: 'Bird',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_unicorn',
      assetPath: 'assets/editor/stickers/fluent_emoji_unicorn.png',
      label: 'Unicorn',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_butterfly',
      assetPath: 'assets/editor/stickers/fluent_emoji_butterfly.png',
      label: 'Butterfly',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_lady_beetle',
      assetPath: 'assets/editor/stickers/fluent_emoji_lady_beetle.png',
      label: 'Lady beetle',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_turtle',
      assetPath: 'assets/editor/stickers/fluent_emoji_turtle.png',
      label: 'Turtle',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_octopus',
      assetPath: 'assets/editor/stickers/fluent_emoji_octopus.png',
      label: 'Octopus',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_dolphin',
      assetPath: 'assets/editor/stickers/fluent_emoji_dolphin.png',
      label: 'Dolphin',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_whale',
      assetPath: 'assets/editor/stickers/fluent_emoji_whale.png',
      label: 'Whale',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_blowfish',
      assetPath: 'assets/editor/stickers/fluent_emoji_blowfish.png',
      label: 'Blowfish',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_tropical_fish',
      assetPath: 'assets/editor/stickers/fluent_emoji_tropical_fish.png',
      label: 'Tropical fish',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_fish',
      assetPath: 'assets/editor/stickers/fluent_emoji_fish.png',
      label: 'Fish',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_shark',
      assetPath: 'assets/editor/stickers/fluent_emoji_shark.png',
      label: 'Shark',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_snail',
      assetPath: 'assets/editor/stickers/fluent_emoji_snail.png',
      label: 'Snail',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_blossom',
      assetPath: 'assets/editor/stickers/fluent_emoji_blossom.png',
      label: 'Blossom',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_sunflower',
      assetPath: 'assets/editor/stickers/fluent_emoji_sunflower.png',
      label: 'Sunflower',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_four_leaf_clover',
      assetPath: 'assets/editor/stickers/fluent_emoji_four_leaf_clover.png',
      label: 'Four leaf clover',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cactus',
      assetPath: 'assets/editor/stickers/fluent_emoji_cactus.png',
      label: 'Cactus',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_mushroom',
      assetPath: 'assets/editor/stickers/fluent_emoji_mushroom.png',
      label: 'Mushroom',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_pizza',
      assetPath: 'assets/editor/stickers/fluent_emoji_pizza.png',
      label: 'Pizza',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_hamburger',
      assetPath: 'assets/editor/stickers/fluent_emoji_hamburger.png',
      label: 'Hamburger',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_french_fries',
      assetPath: 'assets/editor/stickers/fluent_emoji_french_fries.png',
      label: 'French fries',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_hot_dog',
      assetPath: 'assets/editor/stickers/fluent_emoji_hot_dog.png',
      label: 'Hot dog',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_taco',
      assetPath: 'assets/editor/stickers/fluent_emoji_taco.png',
      label: 'Taco',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_burrito',
      assetPath: 'assets/editor/stickers/fluent_emoji_burrito.png',
      label: 'Burrito',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_popcorn',
      assetPath: 'assets/editor/stickers/fluent_emoji_popcorn.png',
      label: 'Popcorn',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_doughnut',
      assetPath: 'assets/editor/stickers/fluent_emoji_doughnut.png',
      label: 'Doughnut',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cookie',
      assetPath: 'assets/editor/stickers/fluent_emoji_cookie.png',
      label: 'Cookie',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_candy',
      assetPath: 'assets/editor/stickers/fluent_emoji_candy.png',
      label: 'Candy',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_lollipop',
      assetPath: 'assets/editor/stickers/fluent_emoji_lollipop.png',
      label: 'Lollipop',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_ice_cream',
      assetPath: 'assets/editor/stickers/fluent_emoji_ice_cream.png',
      label: 'Ice cream',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_soft_ice_cream',
      assetPath: 'assets/editor/stickers/fluent_emoji_soft_ice_cream.png',
      label: 'Soft ice cream',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cupcake',
      assetPath: 'assets/editor/stickers/fluent_emoji_cupcake.png',
      label: 'Cupcake',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_watermelon',
      assetPath: 'assets/editor/stickers/fluent_emoji_watermelon.png',
      label: 'Watermelon',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_strawberry',
      assetPath: 'assets/editor/stickers/fluent_emoji_strawberry.png',
      label: 'Strawberry',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_banana',
      assetPath: 'assets/editor/stickers/fluent_emoji_banana.png',
      label: 'Banana',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_red_apple',
      assetPath: 'assets/editor/stickers/fluent_emoji_red_apple.png',
      label: 'Red apple',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_grapes',
      assetPath: 'assets/editor/stickers/fluent_emoji_grapes.png',
      label: 'Grapes',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_cherries',
      assetPath: 'assets/editor/stickers/fluent_emoji_cherries.png',
      label: 'Cherries',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_rocket',
      assetPath: 'assets/editor/stickers/fluent_emoji_rocket.png',
      label: 'Rocket',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_flying_saucer',
      assetPath: 'assets/editor/stickers/fluent_emoji_flying_saucer.png',
      label: 'Flying saucer',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_airplane',
      assetPath: 'assets/editor/stickers/fluent_emoji_airplane.png',
      label: 'Airplane',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_bicycle',
      assetPath: 'assets/editor/stickers/fluent_emoji_bicycle.png',
      label: 'Bicycle',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_roller_skate',
      assetPath: 'assets/editor/stickers/fluent_emoji_roller_skate.png',
      label: 'Roller skate',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_skateboard',
      assetPath: 'assets/editor/stickers/fluent_emoji_skateboard.png',
      label: 'Skateboard',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_camera',
      assetPath: 'assets/editor/stickers/fluent_emoji_camera.png',
      label: 'Camera',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_movie_camera',
      assetPath: 'assets/editor/stickers/fluent_emoji_movie_camera.png',
      label: 'Movie camera',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_clapper_board',
      assetPath: 'assets/editor/stickers/fluent_emoji_clapper_board.png',
      label: 'Clapper board',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_television',
      assetPath: 'assets/editor/stickers/fluent_emoji_television.png',
      label: 'Television',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_laptop',
      assetPath: 'assets/editor/stickers/fluent_emoji_laptop.png',
      label: 'Laptop',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_light_bulb',
      assetPath: 'assets/editor/stickers/fluent_emoji_light_bulb.png',
      label: 'Light bulb',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_magnet',
      assetPath: 'assets/editor/stickers/fluent_emoji_magnet.png',
      label: 'Magnet',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_gem_stone',
      assetPath: 'assets/editor/stickers/fluent_emoji_gem_stone.png',
      label: 'Gem stone',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_crown',
      assetPath: 'assets/editor/stickers/fluent_emoji_crown.png',
      label: 'Crown',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_ring',
      assetPath: 'assets/editor/stickers/fluent_emoji_ring.png',
      label: 'Ring',
    ),
    EditorStickerAsset(
      id: 'fluent_emoji_sunglasses',
      assetPath: 'assets/editor/stickers/fluent_emoji_sunglasses.png',
      label: 'Sunglasses',
    ),
  ];
}
